1.20.2
FoundationGames/EnhancedBlockEntities pull request #189
Opened 2023-10-03 07:47 UTC by Brokkonaut

2023-10-10 12:01 UTC, wicivo commented
> _ No description provided. _

Can you give the .jar?

2023-10-11 01:48 UTC, Brokkonaut commented
> Can you give the .jar?

[enhancedblockentities-0.9+1.20.2.jar](https://webinterface.cubeside.de/temp/enhancedblockentities-0.9+1.20.2.jar)

2023-10-16 02:53 UTC, MeeniMc requested changes

2023-10-16 02:53 UTC, MeeniMc commented on gradle.properties
>  modmenu_version=7.1.0
```suggestion
modmenu_version=8.0.0
```

2023-10-16 02:53 UTC, MeeniMc commented on gradle.properties
>  modmenu_version=7.1.0
other than that its looking good

2023-10-16 03:38 UTC, MeeniMc approved these changes

2023-10-26 20:39 UTC, MeeniMc commented
I have been using this for several weeks now and it worked flawlessly.

2023-10-28 11:37 UTC, Earthcomputer approved these changes
That `@ModifyVariable` is horrible and needs replacing with something else. But good enough for now.

2023-11-25 22:14 UTC, FoundationGames commented
Looks good, thanks for contributing!
Needs a few changes but I'll take care of them after merge

2023-11-25 22:16 UTC, merged