Add dashloader support. Again.
FoundationGames/EnhancedBlockEntities pull request #73
Opened 2022-01-23 10:05 UTC by alphaqu

Title says it all. 

Not the most clean code every but its designed to change as little of the original code as possible.

2022-01-25 09:10 UTC, PweSol commented
Doesn't work. In fact, it sometimes also does this, instead of making the chest invisible as usual.
![2022-01-25_10 07 50](https://user-images.githubusercontent.com/95942686/150946532-c7bd79ff-7d8b-4e4b-b693-4fe8ca6a105a.png)

2022-01-25 10:43 UTC, alphaqu commented
what mods are you using?

2022-01-25 15:06 UTC, PweSol commented
I cannot replicate the issue anymore. Could have been an issue with cache. However, I'm having still having another issue, which is the chest and the shulker closing animations being glithy.

2022-01-25 15:07 UTC, PweSol commented
And what exactly is this commit supposed to change? I see no difference between it and the stable version, with and without mods.

2022-01-25 16:10 UTC, DragonEggBedrockBreaking commented
> And what exactly is this commit supposed to change? In game, I see no difference in behavior between it and the stable version, with and without mods.

It makes EBE compatible with the DashLoader mod

2022-01-25 16:37 UTC, FoundationGames requested changes

2022-01-25 16:37 UTC, FoundationGames commented on gradle.properties
> +dashloader_definitions_version=3.0-rc14-1.18
These lines should go next to other dependencies

2022-01-25 16:37 UTC, FoundationGames commented on src/main/resources/fabric.mod.json
> -
Wondering as to why the mod json is being reformatted

2022-01-25 16:37 UTC, FoundationGames commented on src/main/java/foundationgames/enhancedblockentities/compat/dashloader/DashDynamicBakedModel.java
> +        }
Making these hardcoded enums for ModelSelector and ModelEffects is really not ideal as stated on the last version of this PR

2022-01-26 11:29 UTC, PweSol commented
> > And what exactly is this commit supposed to change? In game, I see no difference in behavior between it and the stable version, with and without mods.
> 
> It makes EBE compatible with the DashLoader mod

But the stable release works with it anyway.

2022-01-26 16:07 UTC, DragonEggBedrockBreaking commented
> But the stable release works with it. I'm don't understand code, so I don't really know what's going on here anyway.

The stable release is not compatible - sure, it doesn’t crash, but dashloader simply does not work - it has to recache every time and nothing happens. Also chests can look funny.

> `fabric_version=0.44.0+1.18` The latest is 0.46.1+1.18 Is that an issue?

No. The only reason it would be problematic is if the new fabric api changed code in the specific module/code that ebe is using (FAPI is a massive mod) sufficiently to break EBE. The only time this needs to be changed is either then, or if new features are added to the newest version that the mod author wants to use

2022-01-26 22:58 UTC, FoundationGames commented
So far it looks as good as it will be, unless anyone else has any concerns this will be merged when I get the next chance (with subsequent changes)

2022-02-13 13:47 UTC, leocth commented
it has been twenty. one. days.

2022-02-13 20:02 UTC, FoundationGames commented
Please keep in mind that I work on this mod in my spare time (which has been very minimal in recent weeks) and I cannot stick to timeframes or ETAs with the development of my mods.

2022-03-26 20:40 UTC, merged